# Generated by Django 2.0 on 2017-12-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sala', models.IntegerField(blank=True)),
                ('nome_sala', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
