# Generated by Django 2.0 on 2017-12-27 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatweb', '0002_salachat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatweb.SalaChat'),
            preserve_default=False,
        ),
    ]
