# Generated by Django 2.0 on 2017-12-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatweb', '0003_mensagem_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='sala',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='sala',
            field=models.ManyToManyField(blank=True, to='chatweb.SalaChat'),
        ),
    ]
